spring:
  application:
    name: claims-service
server:
  port: 8005
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
insurance:
  vexp:
    types: https://sandbox.api.axa-assistance.com/insurance/vexp/claim_types?contract_id=
baggage:
  claims:
    attachments: https://sandbox.api.axa-assistance.com/insurance/vexp/baggage/claims/{claim_id}/attachments  
logging:
  level:
    org:
      springframework: TRACE



